import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Download, FilePlus2, Plus, RefreshCw, WalletCards, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api } from '../../services/api.js';
import { printDocument } from '../../utils/printDocument.js';

const today = () => new Date().toISOString().slice(0, 10);
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const blankLine = { productId: '', quantity: 1, unitPrice: '', taxRate: 0 };
const blankOrder = { customerId: '', orderDate: today(), notes: '', items: [{ ...blankLine }] };
const statusTone = status => status === 'PAID' ? 'active' : status === 'CONFIRMED' ? 'info' : status === 'PARTIALLY_PAID' ? 'warning' : status === 'CANCELLED' ? 'danger' : '';

export function SalesPage({ section = 'orders' }) {
  const navigate = useNavigate();
  const [orders, setOrders] = useState([]); const [invoices, setInvoices] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [modal, setModal] = useState(null); const [form, setForm] = useState(blankOrder); const [saving, setSaving] = useState(false);
  const isInvoices = section === 'invoices';
  const load = async () => {
    setLoading(true); setError('');
    const results = await Promise.allSettled([api.get('/sales/orders'), api.get('/sales/invoices'), api.get('/contacts', { params: { type: 'CUSTOMER', status: 'ACTIVE' } }), api.get('/products', { params: { status: 'ACTIVE' } })]);
    const [ordersResult, invoicesResult, customersResult, productsResult] = results;
    if (ordersResult.status === 'fulfilled') setOrders(ordersResult.value.data.data);
    if (invoicesResult.status === 'fulfilled') setInvoices(invoicesResult.value.data.data);
    if (customersResult.status === 'fulfilled') setCustomers(customersResult.value.data.data);
    if (productsResult.status === 'fulfilled') setProducts(productsResult.value.data.data);
    const failed = results.find(result => result.status === 'rejected');
    if (failed) setError(failed.reason.response?.data?.message || 'Unable to load sales records.');
    setLoading(false);
  };
  useEffect(() => { load(); }, []);
  const openOrder = () => { setForm({ ...blankOrder, customerId: customers[0]?.id || '', items: [{ ...blankLine, productId: products[0]?.id || '', unitPrice: products[0]?.salesPrice || '' }] }); setModal({ type: 'order' }); setError(''); };
  const updateLine = (index, field, value) => setForm(current => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }));
  const chooseProduct = (index, productId) => { const product = products.find(item => item.id === productId); setForm(current => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, productId, unitPrice: product?.salesPrice || '' } : item) })); };
  const saveOrder = async event => { event.preventDefault(); await submit(`/sales/orders`, form, 'Sales order saved as draft.'); };
  const submit = async (url, body, message) => { setSaving(true); setError(''); try { await api.post(url, body); setModal(null); setNotice(message); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to complete the sales action.'); } finally { setSaving(false); } };
  const confirmOrder = order => submit(`/sales/orders/${order.id}/confirm`, {}, 'Sales order confirmed.');
  const createInvoice = order => { setForm({ invoiceDate: today(), dueDate: today(), notes: '' }); setModal({ type: 'invoice', order }); };
  const saveInvoice = event => { event.preventDefault(); submit(`/sales/orders/${modal.order.id}/invoice`, form, 'Customer invoice created from sales order.'); };
  const confirmInvoice = invoice => submit(`/sales/invoices/${invoice.id}/confirm`, {}, 'Invoice confirmed and journal entry posted.');
  const openPayment = invoice => { setForm({ amount: invoice.outstanding, method: 'BANK', paymentDate: today(), reference: '', notes: '' }); setModal({ type: 'payment', invoice }); };
  const savePayment = event => { event.preventDefault(); submit(`/sales/invoices/${modal.invoice.id}/payment`, form, 'Payment recorded and journal entry posted.'); };
  const printInvoice = invoice => printDocument({ kind: 'Customer Invoice', number: invoice.invoiceNumber, partyLabel: 'Customer', partyName: invoice.customer.name, date: new Date(invoice.invoiceDate).toLocaleDateString('en-IN'), dueDate: invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : '', lines: invoice.salesOrder.items.map(item => ({ product: item.product.name, quantity: item.quantity, unitPrice: item.unitPrice, total: item.total })), subtotal: invoice.subtotal, tax: invoice.tax, total: invoice.total, paid: invoice.paid, status: invoice.status });
  const total = useMemo(() => form.items?.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0) || 0, [form.items]);

  return <><div className="page-header"><div><div className="eyebrow">SALES / {isInvoices ? 'CUSTOMER INVOICES' : 'SALES ORDERS'}</div><h1>{isInvoices ? 'Customer invoices' : 'Sales orders'}</h1><p>{isInvoices ? 'Confirm invoices, record payments and keep receivables current.' : 'Create sales orders and move confirmed orders into customer invoices.'}</p></div><div className="page-header-actions"><button className="secondary-button" onClick={load}><RefreshCw size={15} /> Refresh</button>{!isInvoices && <button className="primary-button" onClick={openOrder}><Plus size={15} /> New sales order</button>}{isInvoices && <button className="primary-button" onClick={() => setNotice('Invoices are created from confirmed sales orders.')}><FilePlus2 size={15} /> New invoice</button>}</div></div>
    {notice && <div className="auth-alert success"><Check size={14} />{notice}<button onClick={() => setNotice('')}><X size={14} /></button></div>}{error && <div className="auth-alert error">{error}</div>}
    <div className="sales-tabs"><button className={!isInvoices ? 'active' : ''} onClick={() => navigate('/sales/orders')}>Sales orders <b>{orders.length}</b></button><button className={isInvoices ? 'active' : ''} onClick={() => navigate('/sales/invoices')}>Customer invoices <b>{invoices.length}</b></button></div>
    <section className="surface users-card">{loading ? <div className="empty-table">Loading sales records...</div> : isInvoices ? <InvoiceTable invoices={invoices} onConfirm={confirmInvoice} onPay={openPayment} onPrint={printInvoice} /> : <OrderTable orders={orders} onConfirm={confirmOrder} onInvoice={createInvoice} />}</section>
    {modal?.type === 'order' && <Modal title="New sales order" subtitle="Choose a customer and add the products from the Sales Order wireframe." onClose={() => setModal(null)}><form onSubmit={saveOrder}><div className="sales-form-grid"><Field label="Customer"><select value={form.customerId} onChange={event => setForm({ ...form, customerId: event.target.value })} required><option value="">Select customer</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></Field><Field label="SO date"><input type="date" value={form.orderDate} onChange={event => setForm({ ...form, orderDate: event.target.value })} required /></Field></div><LineEditor items={form.items} products={products} onChange={updateLine} onProduct={chooseProduct} onAdd={() => setForm({ ...form, items: [...form.items, { ...blankLine }] })} /><div className="sales-total">Total <b>{money(total)}</b></div><Actions saving={saving} onClose={() => setModal(null)} label="Save draft" /></form></Modal>}
    {modal?.type === 'invoice' && <Modal title="Create customer invoice" subtitle={`Invoice will be created from ${modal.order.orderNumber}.`} onClose={() => setModal(null)}><form onSubmit={saveInvoice}><div className="sales-form-grid"><Field label="Invoice date"><input type="date" value={form.invoiceDate} onChange={event => setForm({ ...form, invoiceDate: event.target.value })} required /></Field><Field label="Due date"><input type="date" value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} /></Field></div><div className="linked-record"><b>{modal.order.customer.name}</b><span>{modal.order.items.map(item => `${item.product.name} × ${item.quantity}`).join(', ')}</span><strong>{money(modal.order.total)}</strong></div><Actions saving={saving} onClose={() => setModal(null)} label="Create invoice" /></form></Modal>}
    {modal?.type === 'payment' && <Modal title="Invoice payment" subtitle={`Record payment for ${modal.invoice.invoiceNumber}. Amount due: ${money(modal.invoice.outstanding)}`} onClose={() => setModal(null)}><form onSubmit={savePayment}><div className="sales-form-grid"><Field label="Payment type"><select value="RECEIVE" disabled><option>Receive</option></select></Field><Field label="Partner"><input value={modal.invoice.customer.name} readOnly /></Field><Field label="Amount"><input type="number" min="0.01" max={modal.invoice.outstanding} step="0.01" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} required /></Field><Field label="Payment date"><input type="date" value={form.paymentDate} onChange={event => setForm({ ...form, paymentDate: event.target.value })} required /></Field><Field label="Payment via"><select value={form.method} onChange={event => setForm({ ...form, method: event.target.value })}><option value="BANK">Bank</option><option value="CASH">Cash</option></select></Field></div><Field label="Note"><textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} rows="3" /></Field><Actions saving={saving} onClose={() => setModal(null)} label="Confirm payment" /></form></Modal>}
  </>;
}

function Field({ label, children }) { return <label className="sales-field">{label}{children}</label>; }
function Modal({ title, subtitle, onClose, children }) { return <div className="modal-backdrop"><section className="modal sales-modal"><button className="modal-close" onClick={onClose}><X size={17} /></button><div className="eyebrow">SALES TRANSACTION</div><h2>{title}</h2><p>{subtitle}</p>{children}</section></div>; }
function Actions({ saving, onClose, label }) { return <div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving...' : label}<ArrowRight size={14} /></button></div>; }
function LineEditor({ items, products, onChange, onProduct, onAdd }) { return <div className="sales-line-editor"><div className="sales-line-head"><span>PRODUCT</span><span>QTY</span><span>UNIT PRICE</span><span>TOTAL</span></div>{items.map((item, index) => <div className="sales-line" key={`${index}-${item.productId}`}><select value={item.productId} onChange={event => onProduct(index, event.target.value)} required><option value="">Select product</option>{products.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select><input type="number" min="1" step="1" value={item.quantity} onChange={event => onChange(index, 'quantity', event.target.value)} required /><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={event => onChange(index, 'unitPrice', event.target.value)} required /><b>{money(Number(item.quantity || 0) * Number(item.unitPrice || 0))}</b></div>)}<button type="button" className="text-button" onClick={onAdd}><Plus size={13} /> Add product line</button></div>; }
function OrderTable({ orders, onConfirm, onInvoice }) { return <div className="table-wrap"><table className="sales-order-table"><thead><tr><th>SO NO.</th><th>CUSTOMER</th><th>SO DATE</th><th>PRODUCTS</th><th>TOTAL</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><b className="ref">{order.orderNumber}</b></td><td>{order.customer.name}</td><td>{new Date(order.orderDate).toLocaleDateString('en-IN')}</td><td className="sales-products-cell">{order.items.map(item => item.product.name).join(', ')}</td><td><b>{money(order.total)}</b></td><td><span className={`status-pill ${statusTone(order.status)}`}><i />{order.status}</span></td><td className="sales-actions">{order.status === 'DRAFT' && <button className="compact-button primary-button" onClick={() => onConfirm(order)}>Confirm</button>}{order.status === 'CONFIRMED' && !order.invoice && <button className="compact-button primary-button" onClick={() => onInvoice(order)}>Create invoice</button>}{order.invoice && <span className="table-subtitle">Invoice created</span>}</td></tr>)}</tbody></table>{!orders.length && <div className="empty-table">No sales orders found. Create one to start the workflow.</div>}</div>; }
function InvoiceTable({ invoices, onConfirm, onPay, onPrint }) { return <div className="table-wrap"><table><thead><tr><th>INVOICE</th><th>REFERENCE</th><th>CUSTOMER</th><th>INVOICE DATE</th><th>DUE DATE</th><th>TOTAL</th><th>PAID</th><th>AMOUNT DUE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td><b className="ref">{invoice.invoiceNumber}</b></td><td>{invoice.salesOrder.orderNumber}</td><td>{invoice.customer.name}</td><td>{new Date(invoice.invoiceDate).toLocaleDateString('en-IN')}</td><td>{invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : '—'}</td><td><b>{money(invoice.total)}</b></td><td>{money(invoice.paid)}</td><td><b>{money(invoice.outstanding)}</b></td><td><span className={`status-pill ${statusTone(invoice.status)}`}><i />{invoice.status}</span></td><td className="sales-actions">{invoice.status === 'DRAFT' && <button className="compact-button primary-button" onClick={() => onConfirm(invoice)}>Confirm</button>}{['CONFIRMED', 'PARTIALLY_PAID'].includes(invoice.status) && invoice.outstanding > 0 && <button className="compact-button primary-button" onClick={() => onPay(invoice)}><WalletCards size={13} /> Register payment</button>}{invoice.status === 'PAID' && <button className="compact-button print-button" onClick={() => onPrint(invoice)} title="Download invoice"><Download size={13} /> Download</button>}</td></tr>)}</tbody></table>{!invoices.length && <div className="empty-table">No invoices found. Confirm a sales order and create its invoice.</div>}</div>; }