import { ArrowUpRight, CalendarDays } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageHeader } from '../../components/ui/PageHeader.jsx';
import { StatCard } from '../../components/ui/StatCard.jsx';
import { DataTable } from '../../components/ui/DataTable.jsx';
import { StatusBadge } from '../../components/ui/StatusBadge.jsx';

const chartData = [{ month: 'Apr', sales: 58, purchases: 36 }, { month: 'May', sales: 74, purchases: 46 }, { month: 'Jun', sales: 62, purchases: 42 }, { month: 'Jul', sales: 88, purchases: 58 }, { month: 'Aug', sales: 79, purchases: 52 }, { month: 'Sep', sales: 96, purchases: 61 }];
const transactions = [['INV-2024-0084', 'Aarav Mehta', 'Sales Invoice', '₹31,860', <StatusBadge tone="success">Paid</StatusBadge>], ['BILL-2024-0041', 'Azure Furniture', 'Vendor Bill', '₹17,700', <StatusBadge tone="warning">Pending</StatusBadge>], ['PAY-2024-0028', 'Riya Interiors', 'Payment Received', '₹24,000', <StatusBadge tone="success">Paid</StatusBadge>], ['SO-2024-0096', 'Riya Interiors', 'Sales Order', '₹49,200', <StatusBadge>Draft</StatusBadge>]];

export function DashboardPage() {
  return <><PageHeader eyebrow="OVERVIEW / DASHBOARD" title="Good morning, Nisha" description="A calm view of the numbers that matter for your business today." action={<button className="date-button"><CalendarDays size={15} /> September 2024</button>} /><div className="stat-grid">{[['Total Sales', '₹4,82,650', '+12.8% vs last month', 'green'], ['Total Purchases', '₹2,18,420', '+8.4% vs last month', 'blue'], ['Net Profit', '₹1,46,280', '+18.6% vs last month', 'green'], ['Receivables', '₹68,540', '12 invoices awaiting', 'orange'], ['Payables', '₹42,860', '8 bills due', 'red'], ['Cash / Bank Balance', '₹2,84,920', 'Across 2 accounts', 'teal']].map(card => <StatCard key={card[0]} label={card[0]} value={card[1]} note={card[2]} tone={card[3]} />)}</div><div className="dashboard-grid"><section className="surface chart-card"><div className="section-heading"><div><div className="eyebrow">PERFORMANCE</div><h2>Sales vs purchases</h2></div><span className="muted">Last 6 months</span></div><ResponsiveContainer width="100%" height={240}><BarChart data={chartData} barGap={6}><CartesianGrid stroke="#edf0ef" vertical={false} /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: '#9aa5aa', fontSize: 11 }} /><YAxis hide /><Tooltip cursor={{ fill: '#f5f8f7' }} /><Bar dataKey="sales" fill="#2c9c77" radius={[4, 4, 0, 0]} /><Bar dataKey="purchases" fill="#c8ddd4" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer><div className="legend"><span><i className="sales-dot" />Sales</span><span><i className="purchases-dot" />Purchases</span></div></section><section className="surface insight-card"><div className="eyebrow">OUTSTANDING</div><h2>Keep the cash flowing.</h2><p>There are 12 customer invoices and 8 vendor bills that need attention this month.</p><div className="insight-row"><span>Receivables</span><b>₹68,540</b><ArrowUpRight size={16} /></div><div className="insight-row"><span>Payables</span><b>₹42,860</b><ArrowUpRight size={16} /></div><button className="secondary-button">View outstanding items</button></section></div><section className="surface table-card"><div className="section-heading"><div><div className="eyebrow">ACTIVITY</div><h2>Recent transactions</h2></div><button className="link-button">View all <ArrowUpRight size={14} /></button></div><DataTable columns={['Reference', 'Party', 'Type', 'Amount', 'Status']} rows={transactions} /></section></>;
}
