import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/ui/PageHeader.jsx';
import { api } from '../../services/api.js';

const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
export function PortalRecordsPage({ kind }) {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { api.get('/portal/dashboard').then(response => setRecords(kind === 'invoices' ? response.data.data.invoices : response.data.data.bills)).catch(errorResponse => setError(errorResponse.response?.data?.message || 'Unable to load records.')).finally(() => setLoading(false)); }, [kind]);
  const pay = async record => { const amount = window.prompt(`Enter payment amount (outstanding ${money(record.outstanding)}):`, String(record.outstanding)); if (!amount) return; const method = window.prompt('Payment method: CASH or BANK', 'BANK')?.toUpperCase(); if (!['CASH', 'BANK'].includes(method)) return setError('Choose CASH or BANK.'); try { await api.post('/portal/payments', { amount, method, ...(kind === 'invoices' ? { salesInvoiceId: record.id } : { vendorBillId: record.id }) }); setMessage('Payment recorded successfully.'); const response = await api.get('/portal/dashboard'); setRecords(kind === 'invoices' ? response.data.data.invoices : response.data.data.bills); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to record payment.'); } };
  const title = kind === 'invoices' ? 'My invoices' : 'My bills';
  return <><PageHeader eyebrow={`MY PORTAL / ${kind.toUpperCase()}`} title={title} description="Only records linked to your Contact account are shown." />{message && <div className="auth-alert success">{message}</div>}{error && <div className="auth-alert error">{error}</div>}<section className="surface users-card">{loading ? <div className="empty-table">Loading records...</div> : !records.length ? <div className="empty-table">No records found.</div> : <div className="table-wrap"><table><thead><tr><th>NUMBER</th><th>DATE</th><th>TOTAL</th><th>PAID</th><th>OUTSTANDING</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{records.map(record => <tr key={record.id}><td><b className="ref">{kind === 'invoices' ? record.invoiceNumber : record.billNumber}</b></td><td>{new Date(kind === 'invoices' ? record.invoiceDate : record.invoiceDate).toLocaleDateString('en-IN')}</td><td>{money(record.total)}</td><td>{money(record.paid)}</td><td><b>{money(record.outstanding)}</b></td><td><span className={`status-pill ${record.outstanding ? 'inactive' : 'active'}`}><i />{record.outstanding ? 'Unpaid' : 'Paid'}</span></td><td>{record.outstanding > 0 ? <button className="primary-button compact-button" onClick={() => pay(record)}>Pay</button> : '—'}</td></tr>)}</tbody></table></div>}</section></>;
}
