import { Router } from 'express';
import { authenticate, authorize } from '../middleware/auth.js';
import { contactImageUpload, productImageUpload } from '../middleware/contactUpload.js';
import { archiveAccount, archiveContact, archiveProduct, createAccount, createContact, createProduct, listAccounts, listContacts, listProducts, updateAccount, updateContact, updateProduct } from '../controllers/resourceController.js';
import { archiveJournal, createJournal, createJournalEntry, getJournalEntry, listJournalEntries, listJournals, postJournalEntry, updateJournal } from '../controllers/journalController.js';
import { createAnalyticAccount, createBudget, deleteAnalyticAccount, listAnalyticAccounts, listBudgets, updateAnalyticAccount, updateBudget, updateBudgetStatus } from '../controllers/planningController.js';

const resources = ['contacts', 'products', 'accounts', 'journals', 'analytic-accounts', 'budgets', 'sales', 'purchases', 'payments', 'journal-entries', 'reports'];
export const resourceRoutes = Router();
resourceRoutes.use(authenticate);
resourceRoutes.use(['/contacts', '/products'], authorize('ADMIN', 'ACCOUNTANT'));
resourceRoutes.get('/contacts', listContacts);
resourceRoutes.post('/contacts', contactImageUpload.single('profileImage'), createContact);
resourceRoutes.patch('/contacts/:id', contactImageUpload.single('profileImage'), updateContact);
resourceRoutes.delete('/contacts/:id', archiveContact);
resourceRoutes.get('/products', listProducts);
resourceRoutes.post('/products', productImageUpload.single('imageUrl'), createProduct);
resourceRoutes.patch('/products/:id', productImageUpload.single('imageUrl'), updateProduct);
resourceRoutes.delete('/products/:id', archiveProduct);
resourceRoutes.use('/accounts', authorize('ADMIN', 'ACCOUNTANT'));
resourceRoutes.get('/accounts', listAccounts);
resourceRoutes.post('/accounts', createAccount);
resourceRoutes.patch('/accounts/:id', updateAccount);
resourceRoutes.delete('/accounts/:id', archiveAccount);
resourceRoutes.use(['/journals', '/journal-entries'], authorize('ADMIN', 'ACCOUNTANT'));
resourceRoutes.get('/journals', listJournals);
resourceRoutes.post('/journals', createJournal);
resourceRoutes.patch('/journals/:id', updateJournal);
resourceRoutes.delete('/journals/:id', archiveJournal);
resourceRoutes.get('/journal-entries', listJournalEntries);
resourceRoutes.get('/journal-entries/:id', getJournalEntry);
resourceRoutes.post('/journal-entries', createJournalEntry);
resourceRoutes.post('/journal-entries/:id/post', postJournalEntry);
resourceRoutes.use(['/analytic-accounts', '/budgets', '/sales', '/purchases', '/payments', '/reports'], authorize('ADMIN', 'ACCOUNTANT'));
resourceRoutes.get('/analytic-accounts', listAnalyticAccounts);
resourceRoutes.post('/analytic-accounts', createAnalyticAccount);
resourceRoutes.patch('/analytic-accounts/:id', updateAnalyticAccount);
resourceRoutes.delete('/analytic-accounts/:id', deleteAnalyticAccount);
resourceRoutes.get('/budgets', listBudgets);
resourceRoutes.post('/budgets', createBudget);
resourceRoutes.patch('/budgets/:id', updateBudget);
resourceRoutes.patch('/budgets/:id/status', updateBudgetStatus);
resources.filter(resource => !['contacts', 'products', 'accounts', 'journals', 'journal-entries', 'analytic-accounts', 'budgets'].includes(resource)).forEach(resource => resourceRoutes.get(`/${resource}`, (_request, response) => response.json({ success: true, data: [], message: `${resource} module placeholder` })));
