import { Router } from 'express';
import { authenticate, authorize } from '../middleware/auth.js';
import { contactImageUpload } from '../middleware/contactUpload.js';
import { archiveAccount, archiveContact, archiveProduct, createAccount, createContact, createProduct, listAccounts, listContacts, listProducts, updateAccount, updateContact, updateProduct } from '../controllers/resourceController.js';

const resources = ['contacts', 'products', 'accounts', 'journals', 'analytic-accounts', 'budgets', 'sales', 'purchases', 'payments', 'journal-entries', 'reports'];
export const resourceRoutes = Router();
resourceRoutes.use(authenticate);
resourceRoutes.get('/contacts', listContacts);
resourceRoutes.post('/contacts', contactImageUpload.single('profileImage'), createContact);
resourceRoutes.patch('/contacts/:id', contactImageUpload.single('profileImage'), updateContact);
resourceRoutes.delete('/contacts/:id', archiveContact);
resourceRoutes.get('/products', listProducts);
resourceRoutes.post('/products', createProduct);
resourceRoutes.patch('/products/:id', updateProduct);
resourceRoutes.delete('/products/:id', archiveProduct);
resourceRoutes.use('/accounts', authorize('ADMIN', 'ACCOUNTANT'));
resourceRoutes.get('/accounts', listAccounts);
resourceRoutes.post('/accounts', createAccount);
resourceRoutes.patch('/accounts/:id', updateAccount);
resourceRoutes.delete('/accounts/:id', archiveAccount);
resources.filter(resource => !['contacts', 'products', 'accounts'].includes(resource)).forEach(resource => resourceRoutes.get(`/${resource}`, (_request, response) => response.json({ success: true, data: [], message: `${resource} module placeholder` })));
