import { useEffect, useState } from 'react';
import { Edit3, MoreHorizontal, Plus, Search, ShieldCheck, UserX, X } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader.jsx';
import { api } from '../../services/api.js';

const emptyForm = { name: '', loginId: '', email: '', role: 'CONTACT', password: '', confirmPassword: '' };
const roleLabel = role => role === 'ADMIN' ? 'Administrator' : role === 'ACCOUNTANT' ? 'Accountant' : 'User';
const date = value => new Date(value).toLocaleDateString('en-IN', { dateStyle: 'medium' });

export function AdminUsersPage() {
  const [users, setUsers] = useState([]); const [filters, setFilters] = useState({ search: '', role: 'ALL', status: 'ALL' });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [modal, setModal] = useState(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const response = await api.get('/admin/users', { params: filters }); setUsers(response.data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load users.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [filters.search, filters.role, filters.status]);
  const openCreate = () => { setModal({ type: 'create' }); setForm(emptyForm); setError(''); };
  const openEdit = user => { setModal({ type: 'edit', user }); setForm({ name: user.name, loginId: user.loginId, email: user.email, role: user.role, password: '', confirmPassword: '' }); setError(''); };
  const save = async event => { event.preventDefault(); setSaving(true); setError('');
    try { if (modal.type === 'create') { await api.post('/admin/users', form); setNotice('User created successfully.'); } else { const payload = { name: form.name, email: form.email, role: form.role }; if (form.password) { payload.password = form.password; } await api.patch(`/admin/users/${modal.user.id}`, payload); setNotice('User updated successfully.'); } setModal(null); await load(); }
    catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save user.'); } finally { setSaving(false); }
  };
  const toggle = async user => { try { await api.patch(`/admin/users/${user.id}`, { isActive: !user.isActive }); setNotice(`${user.name} is now ${user.isActive ? 'inactive' : 'active'}.`); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update status.'); } };
  const archive = async user => { if (!window.confirm(`Deactivate ${user.name}?`)) return; try { await api.delete(`/admin/users/${user.id}`); setNotice('User deactivated.'); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to deactivate user.'); } };
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  return <>
    <PageHeader eyebrow="ADMINISTRATION / USER MANAGEMENT" title="Users" description="Manage access to the Urban Furniture system." action={<button className="primary-button" onClick={openCreate}><Plus size={16} /> Create new user</button>} />
    {notice && <div className="auth-alert success">{notice}<button onClick={() => setNotice('')}><X size={14} /></button></div>}{error && <div className="auth-alert error">{error}</div>}
    <section className="surface users-card"><div className="admin-toolbar"><label className="table-search"><Search size={15} /><input value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} placeholder="Search name, Login ID or email" /></label><select value={filters.role} onChange={e => setFilters({ ...filters, role: e.target.value })}><option value="ALL">All roles</option><option value="ADMIN">Administrators</option><option value="ACCOUNTANT">Accountants</option><option value="CONTACT">Users</option></select><select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>{loading ? <div className="empty-table">Loading users...</div> : !users.length ? <div className="empty-table">No users match these filters.</div> : <div className="table-wrap"><table><thead><tr><th>NAME</th><th>LOGIN ID</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>CREATED</th><th>ACTIONS</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><b>{user.name}</b></td><td className="ref">{user.loginId}</td><td>{user.email}</td><td><span className="role-pill"><ShieldCheck size={12} />{roleLabel(user.role)}</span></td><td><span className={`status-pill ${user.isActive ? 'active' : 'inactive'}`}><i />{user.isActive ? 'Active' : 'Inactive'}</span></td><td>{date(user.createdAt)}</td><td><div className="user-actions"><button title="Edit" onClick={() => openEdit(user)}><Edit3 size={14} /></button><button title={user.isActive ? 'Deactivate' : 'Activate'} onClick={() => toggle(user)}><UserX size={14} /></button><button title="Deactivate" onClick={() => archive(user)}><MoreHorizontal size={15} /></button></div></td></tr>)}</tbody></table></div>}</section>
    {modal && <div className="modal-backdrop"><section className="modal admin-user-modal"><button className="modal-close" onClick={() => setModal(null)}><X size={17} /></button><div className="brand modal-brand"><span className="brand-mark">UF</span><span><b>URBAN</b><strong>FURNITURE</strong></span></div><div className="eyebrow">USER MANAGEMENT</div><h2>{modal.type === 'create' ? 'Create new user' : 'Edit user'}</h2><p>Set account details and access level.</p><form onSubmit={save}><label>Name<input name="name" value={form.name} onChange={update} required /></label>{modal.type === 'create' && <label>Login ID<input name="loginId" value={form.loginId} onChange={update} minLength="6" maxLength="12" required /></label>}<label>Email ID<input type="email" name="email" value={form.email} onChange={update} required /></label><label>Role<select name="role" value={form.role} onChange={update}><option value="CONTACT">User</option><option value="ADMIN">Administrator</option><option value="ACCOUNTANT">Accountant</option></select></label><label>Password<input type="password" name="password" value={form.password} onChange={update} minLength="9" required={modal.type === 'create'} placeholder={modal.type === 'edit' ? 'Leave blank to keep current password' : ''} /></label>{modal.type === 'create' && <label>Re-enter password<input type="password" name="confirmPassword" value={form.confirmPassword} onChange={update} required /></label>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : modal.type === 'create' ? 'Create user' : 'Save changes'}</button></div></form></section></div>}
  </>;
}
