import { useEffect, useState } from 'react';
import { Archive, Edit3, Plus, Search, X } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader.jsx';
import { api } from '../../services/api.js';

const types = { SALES: 'Sales', PURCHASE: 'Purchase', BANK: 'Bank', CASH: 'Cash', GENERAL: 'General' };
const emptyForm = { name: '', type: 'SALES', defaultAccountId: '' };

export function JournalsPage() {
  const [journals, setJournals] = useState([]); const [accounts, setAccounts] = useState([]); const [form, setForm] = useState(emptyForm); const [modal, setModal] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [search, setSearch] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [journalResponse, accountResponse] = await Promise.all([api.get('/journals'), api.get('/accounts', { params: { status: 'ACTIVE' } })]); setJournals(journalResponse.data.data); setAccounts(accountResponse.data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load journals.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const open = journal => { setModal(journal ? { type: 'edit', journal } : { type: 'create' }); setForm(journal ? { name: journal.name, type: journal.type, defaultAccountId: journal.defaultDebitAccountId || journal.defaultCreditAccountId || '' } : { ...emptyForm, defaultAccountId: accounts[0]?.id || '' }); setError(''); };
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { if (modal.type === 'create') await api.post('/journals', form); else await api.patch(`/journals/${modal.journal.id}`, form); setModal(null); setNotice('Journal saved successfully.'); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save journal.'); } finally { setSaving(false); } };
  const archive = async journal => { if (!window.confirm(`Delete ${journal.name}?`)) return; try { await api.delete(`/journals/${journal.id}`); setNotice('Journal deleted.'); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to delete journal.'); } };
  const visible = journals.filter(journal => journal.name.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="ACCOUNTING / JOURNALS" title="Journals" description="Configure the journals used to record accounting activity." action={<button className="primary-button" onClick={() => open()}><Plus size={16} /> New journal</button>} />{notice && <div className="auth-alert success">{notice}<button onClick={() => setNotice('')}><X size={14} /></button></div>}{error && <div className="auth-alert error">{error}</div>}<section className="surface users-card"><div className="admin-toolbar"><label className="table-search"><Search size={15} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search journals" /></label></div>{loading ? <div className="empty-table">Loading journals...</div> : !visible.length ? <div className="empty-table">No journals found.</div> : <div className="table-wrap"><table><thead><tr><th>JOURNAL NAME</th><th>TYPE</th><th>DEFAULT ACCOUNT</th><th>ACTIONS</th></tr></thead><tbody>{visible.map(journal => <tr key={journal.id}><td><b>{journal.name}</b><small className="table-subtitle">{journal.code}</small></td><td><span className="role-pill">{types[journal.type] || journal.type}</span></td><td>{journal.defaultDebitAccount?.name || journal.defaultCreditAccount?.name || '—'}</td><td><div className="user-actions"><button title="Edit" onClick={() => open(journal)}><Edit3 size={14} /></button><button title="Delete" onClick={() => archive(journal)}><Archive size={14} /></button></div></td></tr>)}</tbody></table></div>}</section>{modal && <div className="modal-backdrop"><section className="modal admin-user-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setModal(null)}><X size={17} /></button><div className="eyebrow">ACCOUNTING / JOURNALS</div><h2>{modal.type === 'create' ? 'New journal' : 'Edit journal'}</h2><p>Connect this journal to an active Chart of Accounts record.</p><form onSubmit={save}><label>Journal name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></label><label>Journal type<select value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Default account<select value={form.defaultAccountId} onChange={event => setForm({ ...form, defaultAccountId: event.target.value })} required><option value="">Select an account</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Save journal'}</button></div></form></section></div>}</>;
}
